const mongoose=require("mongoose")
const paymentSchema=new mongoose.Schema(
    {
        userId:{
            type:mongoose.Types.ObjectId,
            ref:'User',
            required:true
        },
        paymentId:{
            type:String
        },
        orderId:{
            type:String,
            required:true
        },
        amount:{
            type:Number,
            required:true
        },
        currency:{
            type:String,
            required:true
        },
        receipt:{
            type:String,
        },
        status:{
            type:String,
            required:true
        },
        notes:{
            firstName:{
                type:String
            },
            lastName:{
                type:String
            },
            membershipType:{
                type:String,
                enum:{
                    values:["gold","silver"],
                    message:`{VALUE} is not included in the membership type`
                },
                required:true
            }
        }
    },{timestamps:true}
)
const Payment=mongoose.model("Payment",paymentSchema)
module.exports=Payment